export interface CodeSnippet {
  language: string;
  code: string;
}

export interface PromptStackLayer {
  name: string;
  content: string;
  active: boolean;
  type: 'system' | 'space' | 'memory' | 'history' | 'input' | 'image';
}

export type MessageRole = 'system' | 'user' | 'assistant' | 'tool';

export interface AttachedAudio {
  id: string;
  name: string;
  data: string; // base64 string without data:audio/... prefix
  format: string; // "mp3" or "wav"
  num_frames?: number;
  sample_rate?: number;
}

export interface AssistantAudioResponse {
  data: string;
  format: string;
  transcript?: string;
  id?: string;
}

export interface MessageVersion {
  id: string;
  content: string;
  timestamp: string;
  images?: string[];
  audios?: AttachedAudio[];
  audioResponse?: AssistantAudioResponse;
  modelUsed?: string;
  tokensUsed?: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
  latencyMs?: number;
  promptStackSnapshot?: PromptStackLayer[];
  isThought?: boolean;
  subsequentMessages?: Message[];
}

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: string;
  modelUsed?: string;
  tokensUsed?: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
  latencyMs?: number;
  promptStackSnapshot?: PromptStackLayer[];
  images?: string[]; // base64 images, if any attached
  audios?: AttachedAudio[]; // base64 audio, if any attached
  audioResponse?: AssistantAudioResponse; // Audio generated by model (if audio output enabled)
  isThought?: boolean; // dynamic field indicating if this message is a separate CoT thinking log
  versions?: MessageVersion[];
  currentVersionIndex?: number;
}

export interface CompactChunk {
  id: string;
  lastMsgId: string;
  summary: string;
  timestamp: string;
  originalTokensEst?: number;
  summaryTokensEst?: number;
}

export interface Thread {
  id: string;
  title: string;
  createdAt: string;
  messages: Message[];
  modelId?: string;
  enableAudioOutput?: boolean;
  summary?: string;
  compactedChunks?: CompactChunk[];
  compactedUpToMessageId?: string;
}

export interface Space {
  id: string;
  name: string;
  description: string;
  notes: string; // Persistent project-wide files, notes or codes
  model: string; // e.g., 'openai/gpt-4o'
  temperature: number;
  top_p: number;
  max_tokens: number;
  systemPromptPresetId: string; // references custom active persona
  systemPromptCustom: string; // if they choose to completely override
  threads: Thread[];
  activeThreadId: string;
  pinnedMemoryIds: string[];
  tinkerReasoningEffort?: 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | string;
  tinkerWebSearch?: boolean;
  tinkerShowThinking?: boolean;
  enableThinkingLogs?: boolean;
  includeCoTInContext?: boolean;
  contextScaleTokens?: number; // sliding context window scale limit (in tokens), 0 or >=1000000 = unlimited
  useCompactified?: boolean; // toggle to use compactified summaries up to checkpoint instead of raw history
  presence_penalty?: number; // slider between -2.0 and 2.0 (default 0.0)
  frequency_penalty?: number | null; // slider between -2.0 and 2.0 (default 0.0 or null)
  service_tier?: 'auto' | 'default' | 'flex' | 'fast' | 'priority' | 'scale' | string | null; // processing type (default 'auto')
  enableAudioOutput?: boolean; // toggle to request audio output modality ["text", "audio"]
  openaiVoice?: 'verse' | 'alloy' | 'ash' | 'ballad' | 'coral' | 'echo' | 'sage' | 'shimmer' | string; // audio voice
  openaiAudioFormat?: 'wav' | 'mp3' | 'flac' | string; // audio format
}

export interface Memory {
  id: string;
  title: string;
  content: string;
  tags: string[];
  importance: number; // 1 to 5
  pinned: boolean;
  isActive?: boolean;
  createdAt: string;
  lastUsed?: string;
  images?: string[];
  ocrText?: string;
  visualDescription?: string;
  userMeaning?: string;
}

export interface PersonaPreset {
  id: string;
  name: string;
  description: string;
  prompt: string;
  defaultMode: string; // e.g., 'Code', 'Riff', 'Grief', 'Poster', 'Translation'
}

export interface APIConfig {
  hasTokenEnv: boolean;
  hasOpenAIToken?: boolean;
  hasTinkerKey?: boolean;
  hasOpenRouterKey?: boolean;
  hasGeminiKey?: boolean;
  clientToken: string; // Primary/General API Key (OpenRouter, OpenAI, or Universal)
  tinkerKey?: string; // Thinking Machines / Tinker API Key
  openRouterKey?: string; // OpenRouter API Key
  userName?: string; // Preferred user name (replaces 'the user' in reasoning logs)
}

export interface BubbleColorThemePreset {
  id: string;
  name: string;
  userBg: string;
  userBorder: string;
  userText: string;
  assistantBg: string;
  assistantBorder: string;
  assistantText: string;
}

export interface ChatAppearanceSettings {
  fontFamily: string; // 'inter' | 'jetbrains' | 'fira' | 'playfair' | 'lora' | 'verdana' | 'georgia' | 'system'
  fontSize: number; // in px (11 to 24)
  lineHeight: number; // line-height multiplier (1.35 to 2.0)
  bubbleMaxWidth: string; // e.g. '80%', '85%', '92%', '100%'
  chatWidthMode: 'fluid' | 'square' | 'standard' | 'wide'; // constraint mode for chat column
  userBubbleBg?: string;
  userBubbleBorder?: string;
  userBubbleText?: string;
  assistantBubbleBg?: string;
  assistantBubbleBorder?: string;
  assistantBubbleText?: string;
}
